focus-follows-mouse: true
mouse-follows-focus: false

mouse-swaps-windows: true
mouse-resizes-windows: true

enables-layout-hud: false
enables-layout-hud-on-space-change: false

window-margins: true
window-margin-size: 10

screen-padding-left: 10
screen-padding-right: 10
screen-padding-top: 10
screen-padding-bottom: 10
