# set ctrl + b as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# set alt + shift + h and l to move between windows
bind -n M-H if-shell -F '#{window_start_flag}' 'run-shell "true"' 'previous-window'
bind -n M-L if-shell -F '#{window_end_flag}' 'run-shell "true"' 'next-window'

# set alt + h/j/k/l to move between panes without wrapping
bind -n M-h if-shell -F '#{<=:#{pane_left},0}' 'display-message "Leftmost pane"' 'select-pane -L'
bind -n M-j if-shell -F '#{>=:#{pane_bottom},#{window_height}}' 'display-message "Bottom pane"' 'select-pane -D'
bind -n M-k if-shell -F '#{<=:#{pane_top},0}' 'display-message "Top pane"' 'select-pane -U'
bind -n M-l if-shell -F '#{>=:#{pane_right},#{window_width}}' 'display-message "Rightmost pane"' 'select-pane -R'

# add keymaps to resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# open new windows/panes in the current pane directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# improve copying
setw -g mode-keys vi

# status bar customizations
set-option -g status-position top

# add plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
