# set ctrl + b as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# set alt + shift + h and l to move between windows
bind -n M-H previous-window
bind -n M-L next-window

# add keymaps to resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# add plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
